// Code generated by "enumer -type=ShellType"; DO NOT EDIT.

package utils

import (
	"fmt"
	"strings"
)

const _ShellTypeName = "BashZshFishPowershell"

var _ShellTypeIndex = [...]uint8{0, 4, 7, 11, 21}

const _ShellTypeLowerName = "bashzshfishpowershell"

func (i ShellType) String() string {
	if i < 0 || i >= ShellType(len(_ShellTypeIndex)-1) {
		return fmt.Sprintf("ShellType(%d)", i)
	}
	return _ShellTypeName[_ShellTypeIndex[i]:_ShellTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ShellTypeNoOp() {
	var x [1]struct{}
	_ = x[Bash-(0)]
	_ = x[Zsh-(1)]
	_ = x[Fish-(2)]
	_ = x[Powershell-(3)]
}

var _ShellTypeValues = []ShellType{Bash, Zsh, Fish, Powershell}

var _ShellTypeNameToValueMap = map[string]ShellType{
	_ShellTypeName[0:4]:        Bash,
	_ShellTypeLowerName[0:4]:   Bash,
	_ShellTypeName[4:7]:        Zsh,
	_ShellTypeLowerName[4:7]:   Zsh,
	_ShellTypeName[7:11]:       Fish,
	_ShellTypeLowerName[7:11]:  Fish,
	_ShellTypeName[11:21]:      Powershell,
	_ShellTypeLowerName[11:21]: Powershell,
}

var _ShellTypeNames = []string{
	_ShellTypeName[0:4],
	_ShellTypeName[4:7],
	_ShellTypeName[7:11],
	_ShellTypeName[11:21],
}

// ShellTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ShellTypeString(s string) (ShellType, error) {
	if val, ok := _ShellTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ShellTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ShellType values", s)
}

// ShellTypeValues returns all values of the enum
func ShellTypeValues() []ShellType {
	return _ShellTypeValues
}

// ShellTypeStrings returns a slice of all String values of the enum
func ShellTypeStrings() []string {
	strs := make([]string, len(_ShellTypeNames))
	copy(strs, _ShellTypeNames)
	return strs
}

// IsAShellType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ShellType) IsAShellType() bool {
	for _, v := range _ShellTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
