// Code generated by "enumer -type=DoctorCheckId"; DO NOT EDIT.

package gws2

import (
	"fmt"
	"strings"
)

const _DoctorCheckIdName = "DuplicateWorkspaceDuplicateProject"

var _DoctorCheckIdIndex = [...]uint8{0, 18, 34}

const _DoctorCheckIdLowerName = "duplicateworkspaceduplicateproject"

func (i DoctorCheckId) String() string {
	if i < 0 || i >= DoctorCheckId(len(_DoctorCheckIdIndex)-1) {
		return fmt.Sprintf("DoctorCheckId(%d)", i)
	}
	return _DoctorCheckIdName[_DoctorCheckIdIndex[i]:_DoctorCheckIdIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DoctorCheckIdNoOp() {
	var x [1]struct{}
	_ = x[DuplicateWorkspace-(0)]
	_ = x[DuplicateProject-(1)]
}

var _DoctorCheckIdValues = []DoctorCheckId{DuplicateWorkspace, DuplicateProject}

var _DoctorCheckIdNameToValueMap = map[string]DoctorCheckId{
	_DoctorCheckIdName[0:18]:       DuplicateWorkspace,
	_DoctorCheckIdLowerName[0:18]:  DuplicateWorkspace,
	_DoctorCheckIdName[18:34]:      DuplicateProject,
	_DoctorCheckIdLowerName[18:34]: DuplicateProject,
}

var _DoctorCheckIdNames = []string{
	_DoctorCheckIdName[0:18],
	_DoctorCheckIdName[18:34],
}

// DoctorCheckIdString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DoctorCheckIdString(s string) (DoctorCheckId, error) {
	if val, ok := _DoctorCheckIdNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DoctorCheckIdNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DoctorCheckId values", s)
}

// DoctorCheckIdValues returns all values of the enum
func DoctorCheckIdValues() []DoctorCheckId {
	return _DoctorCheckIdValues
}

// DoctorCheckIdStrings returns a slice of all String values of the enum
func DoctorCheckIdStrings() []string {
	strs := make([]string, len(_DoctorCheckIdNames))
	copy(strs, _DoctorCheckIdNames)
	return strs
}

// IsADoctorCheckId returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DoctorCheckId) IsADoctorCheckId() bool {
	for _, v := range _DoctorCheckIdValues {
		if i == v {
			return true
		}
	}
	return false
}
