// Code generated by "enumer -type=RepositoryType -trimprefix RepositoryType"; DO NOT EDIT.

package gws2

import (
	"fmt"
	"strings"
)

const _RepositoryTypeName = "ProjectWorkspace"

var _RepositoryTypeIndex = [...]uint8{0, 7, 16}

const _RepositoryTypeLowerName = "projectworkspace"

func (i RepositoryType) String() string {
	if i < 0 || i >= RepositoryType(len(_RepositoryTypeIndex)-1) {
		return fmt.Sprintf("RepositoryType(%d)", i)
	}
	return _RepositoryTypeName[_RepositoryTypeIndex[i]:_RepositoryTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RepositoryTypeNoOp() {
	var x [1]struct{}
	_ = x[RepositoryTypeProject-(0)]
	_ = x[RepositoryTypeWorkspace-(1)]
}

var _RepositoryTypeValues = []RepositoryType{RepositoryTypeProject, RepositoryTypeWorkspace}

var _RepositoryTypeNameToValueMap = map[string]RepositoryType{
	_RepositoryTypeName[0:7]:       RepositoryTypeProject,
	_RepositoryTypeLowerName[0:7]:  RepositoryTypeProject,
	_RepositoryTypeName[7:16]:      RepositoryTypeWorkspace,
	_RepositoryTypeLowerName[7:16]: RepositoryTypeWorkspace,
}

var _RepositoryTypeNames = []string{
	_RepositoryTypeName[0:7],
	_RepositoryTypeName[7:16],
}

// RepositoryTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RepositoryTypeString(s string) (RepositoryType, error) {
	if val, ok := _RepositoryTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RepositoryTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RepositoryType values", s)
}

// RepositoryTypeValues returns all values of the enum
func RepositoryTypeValues() []RepositoryType {
	return _RepositoryTypeValues
}

// RepositoryTypeStrings returns a slice of all String values of the enum
func RepositoryTypeStrings() []string {
	strs := make([]string, len(_RepositoryTypeNames))
	copy(strs, _RepositoryTypeNames)
	return strs
}

// IsARepositoryType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RepositoryType) IsARepositoryType() bool {
	for _, v := range _RepositoryTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
